//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTBL
    {
        public int id { get; set; }
        public string AccountKey { get; set; }
        public string AccountName { get; set; }
        public string BussinesName { get; set; }
        public string Phone { get; set; }
        public string OsekMurshe { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string DriverName { get; set; }
        public string CarNumber { get; set; }
        public string DistLineNumber { get; set; }
        public string DistLineName { get; set; }
        public string Mail { get; set; }
        public string Obligo { get; set; }
        public string ObligoBalance { get; set; }
        public string CityCode { get; set; }
        public Nullable<bool> IsSuspend { get; set; }
    }
}
