//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentTBL
    {
        public int id { get; set; }
        public string AgentName { get; set; }
        public Nullable<int> AgentCode { get; set; }
        public string Type { get; set; }
    }
}
