//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class carTBL
    {
        public string CarID { get; set; }
        public string License { get; set; }
        public string TypeCarID { get; set; }
        public string TypeCarName { get; set; }
        public string Des { get; set; }
        public string DriverID { get; set; }
        public string DriverName { get; set; }
        public Nullable<int> DisttLine { get; set; }
        public int id { get; set; }
        public string DriverPhone { get; set; }
        public string maxWeight { get; set; }
    }
}
