//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class catTBL
    {
        public int id { get; set; }
        public string Makat { get; set; }
        public string Des { get; set; }
        public Nullable<int> SubCategoryCode { get; set; }
        public Nullable<int> CategoryCode { get; set; }
        public byte[] PIC { get; set; }
        public string DayToPAG { get; set; }
        public Nullable<int> TypeItem { get; set; }
        public Nullable<System.DateTime> SlaughterDate { get; set; }
        public Nullable<int> TaraCode { get; set; }
        public Nullable<bool> IsArkava { get; set; }
        public Nullable<bool> IsSlaugherDate { get; set; }
        public Nullable<bool> IsKasherToPesach { get; set; }
        public string Notes { get; set; }
    }
}
