//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class GMS_MLAY_SFIRA
    {
        public int id { get; set; }
        public string Makat { get; set; }
        public string Barcode { get; set; }
        public string Des { get; set; }
        public string ManufacturingDate { get; set; }
        public string ExpiryDate { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> MlayNum { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string SlaughterDate { get; set; }
        public Nullable<int> Warehouses { get; set; }
        public Nullable<int> LocationCode { get; set; }
        public string AccountKey { get; set; }
        public string AccountName { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public string WorkerName { get; set; }
    }
}
