//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class InMlayTBL
    {
        public int id { get; set; }
        public string Makat { get; set; }
        public string Des { get; set; }
        public Nullable<double> Neto { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> SlaughterDate { get; set; }
        public Nullable<double> MishtahWeight { get; set; }
        public Nullable<int> SumKartons { get; set; }
        public Nullable<double> TaraWeight { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> MlayNum { get; set; }
        public Nullable<bool> IsInStouck { get; set; }
    }
}
