//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class mexicani_chain
    {
        public int Makat { get; set; }
        public string Dea { get; set; }
        public string SubCategory { get; set; }
        public string Category { get; set; }
    }
}
