//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRowHistoryTBL
    {
        public int id { get; set; }
        public string Makat { get; set; }
        public string Des { get; set; }
        public Nullable<float> SupplyQty { get; set; }
        public Nullable<float> NewQty { get; set; }
        public Nullable<int> PlastonSupplyQty { get; set; }
        public Nullable<int> PlastonNewQty { get; set; }
        public string UniqueID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string StockMovesID { get; set; }
        public string Status { get; set; }
        public string StockID { get; set; }
        public Nullable<float> OriginalSupplyQty { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PlastonCustomerQty { get; set; }
        public Nullable<float> AllocatedQty { get; set; }
        public Nullable<float> OriginallyOrderedQTY { get; set; }
        public Nullable<int> CollectionBag { get; set; }
    }
}
