//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHedTBL
    {
        public int id { get; set; }
        public string OrderNumber { get; set; }
        public string AccountName { get; set; }
        public string AccountKey { get; set; }
        public string UniqueID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AgentKey { get; set; }
        public string AgentName { get; set; }
        public string DistLineNum { get; set; }
        public string DistLineName { get; set; }
        public string Status { get; set; }
        public string Sent { get; set; }
        public string Printed { get; set; }
        public string StockID { get; set; }
        public string OsekMurshe { get; set; }
        public string DriverName { get; set; }
        public string CarNumber { get; set; }
        public string Obligo { get; set; }
        public Nullable<float> ObligoBalance { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Incoming { get; set; }
        public string ERP { get; set; }
        public string PDF { get; set; }
    }
}
