//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlastonTBL
    {
        public int id { get; set; }
        public string Makat { get; set; }
        public string Des { get; set; }
        public Nullable<int> PlastonNewQty { get; set; }
        public Nullable<float> NewQty { get; set; }
        public string PlastonNumber { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SlaughterDate { get; set; }
        public Nullable<int> MlayNum { get; set; }
    }
}
