//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelocateHed
    {
        public int id { get; set; }
        public string OrderNumber { get; set; }
        public string AccountName { get; set; }
        public string AccountKey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string DistLineNum { get; set; }
        public string Status { get; set; }
        public string FromCode { get; set; }
        public string FromName { get; set; }
        public string ToCode { get; set; }
        public string ToName { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    }
}
