//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsTBL
    {
        public int id { get; set; }
        public string TempCode { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.TimeSpan> HourLimit { get; set; }
        public Nullable<float> Faulty { get; set; }
        public Nullable<int> Numerator { get; set; }
        public Nullable<System.DateTime> GlobalProductionDate { get; set; }
        public Nullable<System.DateTime> GlobalDueDate { get; set; }
        public string ShidureComax { get; set; }
        public int SupplierMalyNumerator { get; set; }
        public string RelocateDocNumber { get; set; }
        public int GmsMalyNumerator { get; set; }
        public string CompanyName { get; set; }
        public string OsekMurshe { get; set; }
        public string MinistryOfHealthCode { get; set; }
        public string DriverPhone { get; set; }
        public string TypeCustomer { get; set; }
        public Nullable<bool> IsAgent { get; set; }
        public Nullable<bool> IsDriver { get; set; }
        public Nullable<bool> IsRelocate { get; set; }
        public string Address { get; set; }
        public string App_Version { get; set; }
        public string PasswordPrinter { get; set; }
        public Nullable<int> LastShownOrders { get; set; }
        public string App_Version_Control { get; set; }
        public Nullable<bool> isCharge { get; set; }
        public string App_Version_Prisetim { get; set; }
        public string App_Version_Manager { get; set; }
        public Nullable<bool> IsAddInMlay { get; set; }
        public Nullable<double> WeightTaraForArkava { get; set; }
        public Nullable<bool> IsChangeDayToPag { get; set; }
        public Nullable<bool> IsSelectCustInNeto { get; set; }
        public Nullable<bool> IsChangeManufacturingDate { get; set; }
        public Nullable<bool> IsAddQtyInEnterToProduction { get; set; }
        public Nullable<bool> IsNotShowToMlayInProcess { get; set; }
        public Nullable<bool> IsPrintBarcodeToCust { get; set; }
        public Nullable<bool> IsLocations { get; set; }
        public Nullable<bool> PrintMadbekaByBarcode { get; set; }
        public Nullable<bool> IsSelectWorkerOnPirukNeto { get; set; }
        public Nullable<bool> InsertIntoMlayProduction { get; set; }
        public Nullable<bool> IsCloseOrderWhenNotEverythingIsCollected { get; set; }
        public Nullable<bool> InsertMlayByBarcode { get; set; }
    }
}
