//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitbar
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public int id { get; set; }
        public int SubCategoryCode { get; set; }
        public string SubCategoryName { get; set; }
        public Nullable<int> Category { get; set; }
    }
}
